custom:
  database:
    path: 127.0.0.1:3306
    name: demo-auth
    params: autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
