spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: demo-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${custom.database.path}/${custom.database.name}?${custom.database.params}
    username: ${custom.database.username}
    password: ${custom.database.password}
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=2000)
    hikari:
      maximum-pool-size: 20
      connection-test-query: SELECT 1;
      connection-timeout: 60000


server:
  port: 13280

swagger:
  base:
    package:
      path: com.demo.auth.ws.controller

mybatis:
  check-config-location: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.demo.auth.bean

eureka:
  client:
    serviceUrl:
      defaultZone: ${custom.cloud.eureka.service-url}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 30
logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: info
    com.demo.auth.dao.mapper: debug